# Generated by Django 5.1.2 on 2024-11-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_recommendation', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop_recommendation.cropprediction'),
        ),
    ]
